### ISSUE TITLE
Network Error: 400

### ISSUE THREAD

**Issue by rich-howell** [otaviocc/obsidian-microblog#10]
Hello,

I recently added this plugin to Obsidian as a way to publish to my blog from Windows, however there is a small issue I found when testing. 

I created a new note and added a title then attempted to publish the post, I get the following error 

![image](https://github.com/otaviocc/obsidian-microblog/assets/22135084/9cb75af5-89c4-4238-8644-2ebf214f39c1)

Which seems to suggest there was a network problem, however It turns out that you can't publish a note from Obsidian without a body, a title is not enough and renders the above error message, it might be good if there was a way for this to be caught and the user informed that a blank body isn't allowed.

**Comment by otaviocc** [comment]
Good point. I'll fix it. Thanks!
