### ISSUE TITLE
No publish action with v1.7.0

### ISSUE THREAD

**Issue by todorvlaev** [otaviocc/obsidian-microblog#11]
Hi,

At the moment I don't see a publish action available via the command switcher. I do get the action for synchronising categories.

I'm not sure when this has broken. Last time I posted successfully was on 2023-08-17. Since then likely the plugin and Obsidian have updated.

Tried logging in and out, as well re-installing the plugin and restarting Obsidian. No dice.

System info:
- Micro.publish 1.7.0
- Obsidian 1.4.9 (Insider build)
- macOS 13.5.1, iPad OS 17.0 beta something, iOS 16.6
- Same vault

**Comment by otaviocc** [comment]
As we talked (via Micro.blog or Mastodon, I don't remember now), the command only appears on Edit mode, not in Preview mode. Thanks!
