### ISSUE TITLE
Failed to Fetch

### ISSUE THREAD

**Issue by aeluabik** [otaviocc/obsidian-microblog#5]
Well... that's basically the issue. The API token is set, but I couldn't post a note, got this error instead
`Failed to fetch`

**Comment by ianbetteridge** [comment]
I have the same issue. Publishing was working, but in the past few days all I get is a failed to fetch error.

**Comment by otaviocc** [comment]
Hi @aeluabik and @ianbetteridge, how are you? I haven't encountered this issue yet, but I managed to reproduce it by invalidating my [Micro.blog App Token](https://micro.blog/account/apps). Could you please log out in the Obsidian Settings and then log in again using your Micro.blog App Token?

![Screenshot 2023-09-12 at 14 51 10](https://github.com/otaviocc/obsidian-microblog/assets/139272/a277e05b-4596-4fcf-adff-31f67fe0f7fd)

Please let me know if that doesn't resolve the issue, and we can proceed with debugging using logs.

**Comment by ianbetteridge** [comment]
Hi @otaviocc, thanks for responding! I've tried logging out then back in with the same app token, and also tried revoking that app token and then generating a new one and still get the same error.

Not sure if this would have an impact, but I'm using Micro.blog on my own domain rather than a micro.blog sub-domain.

Happy to help with logs etc - let me know what you need.

**Comment by ianbetteridge** [comment]
OK!!! You can ignore that last point -- it is now working again. What I hadn't done was close and reopen Obsidian -- it looks like that is necessary in order to make a new token work if you're replacing it. So this looks like a closed issue to me -- thanks again for your help!

**Comment by otaviocc** [comment]
[Version 2.3.2](https://github.com/otaviocc/obsidian-microblog/releases/tag/2.3.2) fixes a problem with long posts, which would result in Failed to Fetch. Let me know if you face this issue again. Thanks.
