### ISSUE TITLE
Post Updates

### ISSUE THREAD

**Issue by JPhilpin** [otaviocc/obsidian-microblog#9]
GREAT Plugin Otavio - has something changed? I sa there was an update in past 24 hours.

When I installed plugin - I could write and publish from Obsidian AND if I updated the words in Obsidian and republished - the original post updates.

For me it is now republishing the post as a new one 

Could something I have done changed behavior?  I cant find any obvious setting.

**Comment by otaviocc** [comment]
[Version 2.0.0](https://github.com/otaviocc/obsidian-microblog/releases/tag/2.0.0) introduced updating posts (and [version 2.1.0](https://github.com/otaviocc/obsidian-microblog/releases/tag/2.1.0) publishing and updating pages). This closes this issue. Thanks!
